---
ansible:
  playbook: playbook.yml

docker:
  containers:
  - name: concept-01
    ansible_groups:
      - group1
    image: ubuntu
    image_version: latest
  - name: concept-02
    ansible_groups:
      - group2
    image: ubuntu
    image_version: latest
